# Generated by Django 6.1 on 2026-08-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_cm',
            field=models.FloatField(default=170),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_kg',
            field=models.FloatField(default=70),
        ),
    ]
